.TH AMDGPU-PLOT 1 "October 2019" "amdgpu-utils" "User Commands"
.SH NAME
amdgpu-plot \- continuously update and plot critical GPU parameters as a function of time.
.SH SYNOPSIS
.B amdgpu-plot
.RB [ \-\-debug ]
.br
.B amdgpu-plot
.BR \-\-help | \-\-about
.br
.B amdgpu-plot
.RB [ \-\-no_fan "] [" \-\-stdin "] [" \-\-simlog "] [" \-\-ltz "] [" \-\-sleep " \fIN\fP]
.SH DESCRIPTION
.B amdgpu-plot
will continuously plot a trend of critical GPU parameters for all compatible AMD GPUs.

.SH OPTIONS
.TP
.BR " \-\-about"
Will display details about 
.B amdgpu-plot\fP.
.TP
.BR " \-\-ltz"
Use local time zone instead of UTC for displays and logging.
.TP
.BR " \-\-no_fan"
Will exclude fan information from the display.  Useful with watercooled GPUs.
.TP
.BR " \-\-stdin"
Will read data from stdin.  This is useful to display plots of a logfile save with \fBamdgpu-monitor\fR.
.TP
.BR " \-\-simlog"
When used with the \-\-stdin option, it will simulate the reading of data from the logfile at a rate
define by \-\-sleep.
.TP
.BR " \-\-sleep " \fIN\fP
Spcifies N, the number of seconds to sleep between updates.
.TP
.BR " \-\-debug"
Will display additional details while checking the user environment.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.SH BUGS
Known to not work well with Fiji ProDuo cards and will issue warning messages for Fiji Nano cards.
.SH AUTHOR
.nf
Ricks-Lab <rueikes.homelab@gmail.com>
.fi
.SH "SEE ALSO"
.BR amdgpu (4)
.BR amdgpu-monitor (1)
.SH AVAILABILITY
The amdgpu-plot command is part of the amdgpu-utils package and is available from
https://github.com/Ricks-Lab/amdgpu-utils
