.TH AMDGPU-CHK 1 "October 2019" "amdgpu-utils" "User Commands"
.SH NAME
amdgpu-chk \- verifies if the environment is compatible with amdgpu-utils
.SH SYNOPSIS
.B amdgpu-chk
.RB [ \-\-debug ]
.br
.B amdgpu-chk
.BR \-\-help | \-\-about
.SH DESCRIPTION
.B amdgpu-chk
will check the user environment for compatibility with amdgpu-utils.

.SH OPTIONS
.TP
.BR " \-\-about"
Will display details about 
.B amdgpu-chk\fP.
.TP
.BR " \-\-debug"
Will display additional details while checking the user environment.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.SH BUGS
No known bugs.
.SH AUTHOR
.nf
Ricks-Lab <rueikes.homelab@gmail.com>
.fi
.SH "SEE ALSO"
.BR amdgpu (4)
.SH AVAILABILITY
The amdgpu-chk command is part of the amdgpu-utils package and is available from
https://github.com/Ricks-Lab/amdgpu-utils
