.TH AMDGPU-PAC 1 "October 2019" "amdgpu-utils" "User Commands"
.SH NAME
amdgpu-pac \- program and control compatible AMD GPUs

.SH SYNOPSIS
.B amdgpu-pac
.RB [ \-\-help "] [" \-\-about "]"
.br
.B amdgpu-pac
.RB [ \-\-execute_pac "] [" \-\-no_fan "] [" \-\-force_write "] [" \-\-debug "]

.SH CONFIGURATION
All amdgpu-utils require that compatible GPU cards and drivers are installed and that
the feature to access them is enabled.  This can be accomplished by adding
amdgpu.ppfeaturemask=0xfffd7fff to the GRUB_CMDLINE_LINUX_DEFAULT value in
/etc/default/grub and executing update-grub.

.SH DESCRIPTION
.B amdgpu-pac
will present the user with a gui to modify the operating conditions of compatible AMD GPUs.
With this utility, the user can change GPU power limit, S-Clk and M-Clk P-state/Curve definitions,
P-state masks, fan speed, and power performance mode.
By default, the commands to be written to a GPU are written to a bash file for the user to inspect
and run with root permissions.

.SH OPTIONS
.TP
.BR " \-\-about"
Will display details about
.B amdgpu-pac\fP.
.TP
.BR " \-\-execute_pac"
Will execute a bash file created with commands written to the AMD driver files to modify the operating
conditions of the selected GPU/GPUs.  The default behavior is to only create the bash files for the user
to execute.
.TP
.BR " \-\-no_fan"
Will exclude fan information from the display and will not include fans in writing or resetting
GPU operating conditions.
.TP
.BR " \-\-force_write"
Will result in all parameters being writen to the selected GPU/GPUs instead of the default behavior of
only writing changes.
.TP
.BR " \-\-debug"
Will display additional details useful in troubleshooting.
.TP
.BR \-h , " \-\-help"
Display help text and exit.

.SH BUGS
Known to not work well with Fiji ProDuo cards and will issue warning messages for Fiji Nano cards.  The
display of P-state masks is always the defaults, not the actual values.
Please report any additional bugs/issues at https://github.com/Ricks-Lab/amdgpu-utils

.SH "SEE ALSO"
.BR amdgpu (4),
.BR amdgpu-monitor (1)

.SH AVAILABILITY
The amdgpu-pac command is part of the amdgpu-utils package and is available from
https://github.com/Ricks-Lab/amdgpu-utils
