.TH AMDGPU-LS 1 "October 2019" "amdgpu-utils" "User Commands"
.SH NAME
amdgpu-ls \- display details about amdgpu compatible GPU cards

.SH SYNOPSIS
.B amdgpu-ls
.RB [ \-\-debug ]
.br
.B amdgpu-ls
.RB [ \-\-help "] [" \-\-about "]"
.br
.B amdgpu-ls
.RB [ \-\-clinfo "] [" \-\-no_fan "] [" \-\-ppm "] [" \-\-pstate "]

.SH CONFIGURATION
All amdgpu-utils require that compatible GPU cards and drivers are installed and that
the feature to access them is enabled.  This can be accomplished by adding
amdgpu.ppfeaturemask=0xfffd7fff to the GRUB_CMDLINE_LINUX_DEFAULT value in
/etc/default/grub and executing update-grub.

.SH DESCRIPTION
.B amdgpu-ls
displays most relevant parameters for installed and compatible AMD GPUs.
The default behavior is to list relevant base parameters by GPU.

.SH OPTIONS
.TP
.BR " \-\-about"
Will display details about 
.B amdgpu-ls\fP.
.TP
.BR " \-\-clinfo"
If the clinfo package is installed, openCL details will be included in the output
for each compatible AMD GPU.
.TP
.BR " \-\-no_fan"
Will exclude fan information from the display.  Useful with watercooled GPUs.
.TP
.BR " \-\-ppm"
Will display descriptions of available power performance modes.
.TP
.BR " \-\-pstate"
Will display P-state table for system and memory clocks.
.TP
.BR " \-\-debug"
Will display additional details useful in troubleshooting.
.TP
.BR \-h , " \-\-help"
Display help text and exit.

.SH BUGS
Known to not work well with Fiji ProDuo cards and will issue warning messages for Fiji Nano cards.
Please report any additional bugs/issues at https://github.com/Ricks-Lab/amdgpu-utils

.SH "SEE ALSO"
.BR clinfo (1),
.BR amdgpu (4)

.SH AVAILABILITY
The amdgpu-ls command is part of the amdgpu-utils package and is available from
https://github.com/Ricks-Lab/amdgpu-utils
