#!/usr/bin/env python3
"""amdgpu-plot  -  Plot GPU parameter curves

    A utility to plot GPU curves

    Copyright (C) 2019  RueiKe

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
__author__ = "RueiKe"
__copyright__ = "Copyright (C) 2019 RueiKe"
__credits__ = []
__license__ = "GNU General Public License"
__program_name__ = "amdgpu-plot"
__version__ = "v2.4.1"
__maintainer__ = "RueiKe"
__status__ = "Development"

from matplotlib.ticker import AutoLocator
from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo as FigureCanvas
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import GLib, Gtk, Gdk
import argparse
import re
import subprocess
import os
import platform
import sys
import csv
import time
from GPUmodules import env
from datetime import datetime
import glob 
import shutil 
from pathlib import Path



class GuiComponents:
    def __init__(self, gpu_list):
        self.gui_components = {}

        #header:  ['Time', 'Card#', 'model_display', 'loading', 'power', 'power_cap', 'energy', 'temp', 'vddgfx',
        #'fan_pwm', 'sclk_f', 'sclk_ps', 'mclk_f', 'mclk_ps', 'ppm']

        self.gui_components["energy_bar"] = {}
        self.gui_components["sclk_pstate_status"] = {}
        self.gui_components["sclk_pstate_status"]["df_name"] = 'sclk_ps'
        self.gui_components["mclk_pstate_status"] = {}
        self.gui_components["mclk_pstate_status"]["df_name"] = 'mclk_ps'
        self.gui_components["temp_status"] = {}
        self.gui_components["temp_status"]["df_name"] = 'temp'
        self.gui_components["card_plots"] = {}
        #for k,v in gpu_list.items():
            #self.gui_components["card_plots"][k] = {}
        for gpu in gpu_list:
            self.gui_components["card_plots"][gpu] = {}
        return


class GPUPlotWindow(Gtk.Window):
    def __init__(self, gc, num_gpus, df):
        Gtk.Window.__init__(self, title="amdgpu-plot")
        self.set_border_width(1)
        icon_file = os.path.join(env.gut_const.PATH, "icons", "amdgpu-monitor.icon.png")
        if(os.path.isfile(icon_file) == True):
            self.set_icon_from_file(icon_file)
        #self.set_default_size(1000, 100*num_gpus)
        grid = Gtk.Grid()
        grid.override_background_color(Gtk.StateType.NORMAL, Gdk.RGBA(0.4,0.4,0.4,1))
        self.add(grid)

        row = 0
        # Top Bar - Energy
        gc.gui_components["energy_bar"]["gtk_obj"] = Gtk.Label()
        gc.gui_components["energy_bar"]["gtk_obj"].set_markup("<big><b>Card " + "Energy" + "</b>" + "</big>")
        gc.gui_components["energy_bar"]["gtk_obj"].override_color(Gtk.StateFlags.NORMAL, Gdk.RGBA(1.0, 1.0, 1.0, 1.0))
        gc.gui_components["energy_bar"]["gtk_obj"].set_property("margin-top", 1)
        gc.gui_components["energy_bar"]["gtk_obj"].set_property("margin-bottom", 1)
        gc.gui_components["energy_bar"]["gtk_obj"].set_property("margin-right", 4)
        gc.gui_components["energy_bar"]["gtk_obj"].set_property("margin-left", 4)
        gc.gui_components["energy_bar"]["gtk_obj"].set_alignment(0.5, 0.5)
        lbox = Gtk.Box(spacing=6)
        lbox.override_background_color(Gtk.StateType.NORMAL, Gdk.RGBA(.20,.40,.60,1.0))
        lbox.set_property("margin-top", 1)
        lbox.set_property("margin-bottom", 1)
        lbox.set_property("margin-right", 1)
        lbox.set_property("margin-left", 1)
        lbox.pack_start(gc.gui_components["energy_bar"]["gtk_obj"], True, True, 0)
        grid.attach(lbox, 1, row, 4, 1)
        row += 1

        plot_top_row = row
        for v in [gc.gui_components["sclk_pstate_status"], gc.gui_components["mclk_pstate_status"], gc.gui_components["temp_status"]]:
            v["figure"], v["ax1"] = plt.subplots()
            v["ax1"].set_ylabel('MHz', color='b')
            v["ax1"].tick_params('y', colors='b')
            v["ax2"] = v["ax1"].twinx()
            v["ax2"].set_ylabel('MHz', color='r')
            v["ax2"].tick_params('y', colors='r')

            latest = df['Time'].iloc[-1]
            last_val_df = df[df['Time'].isin([latest])].loc[:,['Card#', v['df_name']]]
            data_val = last_val_df[v['df_name']].values
            label_val = last_val_df['Card#'].values
            
            ind = np.arange(num_gpus)  # the x locations for the groups
            width = 0.35       # the width of the bars

            v["figure"], v["ax1"]  = plt.subplots()
            rects1 = v["ax1"].bar(ind, data_val, width, color='#808080', tick_label=label_val)

            v["canvas"] = FigureCanvas(v["figure"])  # a Gtk.DrawingArea
            v["canvas"].set_size_request(200, 200)

            lbox = Gtk.Box(spacing=6)
            lbox.override_background_color(Gtk.StateType.NORMAL, Gdk.RGBA(1,1,1,1.0))
            lbox.set_property("margin-top", 3)
            lbox.set_property("margin-bottom", 3)
            lbox.set_property("margin-right", 3)
            lbox.set_property("margin-left", 3)
            lbox.pack_start(v["canvas"], True, True, 0)

            grid.attach(lbox, 1, row, 1, 1)
            row += 1

        row = plot_top_row
        for k,v in gc.gui_components["card_plots"].items():
            df[df["Card#"].isin([0])]

            v["figure"], v["ax1"] = plt.subplots()
            v["ax1"].set_ylabel('Loading/Power/Temp', color='b')
            v["ax1"].tick_params('y', colors='b')
            v["ax2"] = v["ax1"].twinx()
            v["ax2"].set_ylabel('MHz', color='g')
            v["ax2"].tick_params('y', colors='g')

            #header:  ['Time', 'Card#', 'model_display', 'loading', 'power', 'power_cap', 'energy', 'temp', 'vddgfx',
            #'fan_pwm', 'sclk_f', 'sclk_ps', 'mclk_f', 'mclk_ps', 'ppm']
            v["ax1"].plot(df[df["Card#"].isin([k])].loc[:,['Time']], df[df["Card#"].isin([k])].loc[:,['power']],
                    color='b', linewidth=1, label='pow')
            v["ax1"].plot(df[df["Card#"].isin([k])].loc[:,['Time']], df[df["Card#"].isin([k])].loc[:,['loading']],
                    color='k', linewidth=1)
            v["ax1"].plot(df[df["Card#"].isin([k])].loc[:,['Time']], df[df["Card#"].isin([k])].loc[:,['temp']],
                    color='#808080', linewidth=1)
            v["ax2"].plot(df[df["Card#"].isin([k])].loc[:,['Time']], df[df["Card#"].isin([k])].loc[:,['vddgfx']],
                    color='#606060', linewidth=1)
            v["ax2"].plot(df[df["Card#"].isin([k])].loc[:,['Time']], df[df["Card#"].isin([k])].loc[:,['sclk_f']],
                    color='g', linewidth=1)
            v["ax2"].plot(df[df["Card#"].isin([k])].loc[:,['Time']], df[df["Card#"].isin([k])].loc[:,['mclk_f']],
                    color='y', linewidth=1)

            v["canvas"] = FigureCanvas(v["figure"])  # a Gtk.DrawingArea
            v["canvas"].set_size_request(600, 200)

            lbox = Gtk.Box(spacing=6)
            lbox.override_background_color(Gtk.StateType.NORMAL, Gdk.RGBA(1,1,1,1.0))
            lbox.set_property("margin-top", 3)
            lbox.set_property("margin-bottom", 3)
            lbox.set_property("margin-right", 3)
            lbox.set_property("margin-left", 3)
            lbox.pack_start(v["canvas"], True, True, 0)

            grid.attach(lbox, 2, row, 3, 1)
            row += 1




def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--about", help="README", action="store_true", default=False)
    parser.add_argument("--logfile", help="Specify logfile as source data", type=str, default="")
    parser.add_argument("-d", "--debug", help="Debug output", action="store_true", default=False)
    args = parser.parse_args()


    # About me
    if args.about == True :  
        print(__doc__ )
        print("Author: ", __author__ )
        print("Copyright: ", __copyright__)
        print("Credits: ", __credits__)
        print("License: ", __license__)
        print("Version: ", __version__)
        print("Maintainer: ", __maintainer__)
        print("Status: ", __status__)
        sys.exit(0)

    env.gut_const.PATH = os.path.dirname(str(Path(__file__).resolve()))
    env.gut_const.DEBUG = args.debug

    if env.gut_const.check_env() < 0:
        print("Error in environment. Exiting...")
        sys.exit(-1)

    print("WARNING: This is non-functional code, currently under development")

    df = pd.read_csv(args.logfile, delimiter='|')
    num_gpus = df['Card#'].nunique()
    gpu_list = df['Card#'].unique()
    if args.debug: print("gpu_list: ", gpu_list)

    if args.debug: print(df.dtypes)
    if args.debug: print(df.columns)
    if args.debug: print("num_gpus: ", df['Card#'].nunique())

    # Define graph components
    gc = GuiComponents(gpu_list)

    # Display Gtk style Monitor
    gplot = GPUPlotWindow(gc, num_gpus, df)
    #print(gc.gui_components)
    gplot.connect("delete-event", Gtk.main_quit)
    gplot.show_all()
    Gtk.main()

if __name__ == "__main__":
    main()
